steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/stunning-saga-386406/bnm23/bnm2:latest",
        ".",
      ]

  # Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/stunning-saga-386406/bnm23/bnm2:latest",
      ]

  # Deploy the image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "flask-server"
      - "--image"
      - "us-central1-docker.pkg.dev/stunning-saga-386406/bnm23/bnm2:latest"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "5000"
options:
  logging: CLOUD_LOGGING_ONLY